select TITLE, a.BOARD_ID, REPLY_ID, b.WRITER_ID, b.CONTENTS, b.CREATED_DATE
from USED_GOODS_BOARD a, USED_GOODS_REPLY b
where a.BOARD_ID = b.BOARD_ID and YEAR(a.CREATED_DATE) = 2022 and MONTH(a.CREATED_DATE) = 10
order by b.CREATED_DATE asc, TITLE asc;